name: Draw Keymap
on:
  push:
    branches:
      - senyoku-mainline
    paths:
      - 'keyboards/zsa/voyager/keymaps/senyoku/keymap.c'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install qmk keymap-drawer

      - name: Parse and Draw Keymap
        run: |
          # 1. Use QMK CLI to convert your C file into QMK JSON
          qmk c2json -kb zsa/voyager -km senyoku keyboards/zsa/voyager/keymaps/senyoku/keymap.c > keymap.json

          # 2. Parse the QMK JSON into a Keymap Drawer YAML
          keymap parse -q keymap.json > keymap.yaml

          # 3. Draw the final SVG
          keymap draw keymap.yaml > voyager_keymap.svg

      - name: Commit updated SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Auto] Update keymap SVG diagram"
          file_pattern: "voyager_keymap.svg"
